name: siajte_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: 5.7.0
  google_fonts: 4.0.3
  dio: 5.1.1
  shared_preferences: 2.1.0
  chips_choice: 3.0.0
  im_stepper: 1.0.1+1
  flutter_speed_dial: ^6.2.0
  webview_flutter: 4.2.1
  path_provider: 2.0.15
  flutter_local_notifications: 14.1.1
  timezone: 0.9.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

